spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes: []
  config:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,zipkin,httptrace
  endpoint:
    health:
      show-details: always
    tracing:
      sampling:
        probability: 1.0
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:serviceUrl:
      defaultZone: "http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/"
