spring:
    application:
      name: mcp-server
ai:
    mcp:
      server:
        stdio: false
        enabled: true
        type: SYNC
        name: mcp-server
        version: 1.0.0
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/messages
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,zipkin,httptrace
  endpoint:
    health:
      show-details: always
    #tracing:
      #sampling:
        #probability: 1.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/"
