spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus, refresh,info
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/"
