server:
  port: 8001
spring:
  ai:
    model:
      chat: openai
    openai:
      api-key: AIzaSyAQ57WkJWLBXWmBXSYnjGl3w2PGSLFJFGs
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            server:
              url: "http://localhost:8081"
