server:
  eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  ai:
    model:
      chat: openai
    openai:
      api-key: ${GOOGLE_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            server:
              url: "http://localhost:8081"
