spring:
  application:
    name: ia-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  ai:
    model:
      chat: openai
    openai:
      api-key: ${GOOGLE_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            server:
              url: "http://localhost:8090"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    
resilience4j:
  ratelimiter:
    instances:
      ia-minute:
        limit-for-period: 15
        limit-refresh-period: 1m
        timeout-duration: 0
  circuitbreaker:
    instances:
      ia-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 15s
  retry:
    instances:
      ia-service:
        max-attempts: 2
        wait-duration: 1s
  bulkhead:
    instances:
      ia-service:
        max-concurrent-calls: 2
        max-wait-duration: 0
