eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      enabled: true
      show-details: always
      show-components: always
  tracing:
      sampling:
        probability: 1.0